# Generated by Django 4.0.4 on 2022-06-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_subcategory', models.CharField(default='', max_length=50)),
                ('product_desc', models.CharField(max_length=500)),
                ('product_price', models.FloatField(default=0)),
                ('product_image', models.ImageField(default='', upload_to='shop/prod_images')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
