# Generated by Django 4.0.4 on 2022-12-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Phone_no',
            field=models.IntegerField(default='0'),
        ),
    ]
