# Generated by Django 4.0.4 on 2022-12-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_customuser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_contact', models.IntegerField()),
                ('Business_email', models.CharField(max_length=50)),
                ('Business_name', models.CharField(max_length=100)),
                ('Business_address', models.TextField()),
                ('Business_type', models.CharField(choices=[('Trading', 'Trading'), ('Photography', 'Photography')], default='NONE', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='shop.businessuser'),
        ),
    ]
