# Generated by Django 4.0.4 on 2023-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.TextField(default=''),
        ),
    ]
